
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[607] =
    {   0,
       77,   77,   81,   80,   79,   78,   77,   80,   77,   80,
       77,   77,   77,   79,   77,   77,   77,    0,   77,    0,
       77,   77,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   77,   77,   77,
        0,   76,   76,   76,   76,   76,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   76,   76,   76,   76,    0,   77,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   77,   76,   76,   76,    0,   76,
       76,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   63,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   77,   77,   76,    0,   76,   76,    0,    0,
        0,    0,   76,   76,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   64,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   29,    0,    0,   19,    0,    0,    0,    0,

        0,    0,    0,    3,    0,    0,    0,   55,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   49,    0,    0,    0,   77,
       76,   76,   76,   76,   76,   76,   76,    0,    0,    0,
        0,   30,    0,    0,   20,    0,    0,    0,    0,    0,
        0,    4,    0,    0,   56,   10,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   50,    0,    0,    0,    0,    0,    0,   37,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   39,
        0,    0,    0,    0,   31,    0,    0,   65,   71,   69,

        0,   67,    5,    0,    0,    0,   76,   76,   76,    0,
        0,    0,    0,    0,    0,   38,    0,    0,    0,    0,
        0,    0,    0,    0,   40,    0,    0,    0,    0,   32,
        0,    0,   66,   72,   70,    0,   68,    6,    0,   27,
        0,   11,    0,    0,    0,    0,    0,   45,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   35,    0,
       61,    0,    0,    0,    0,    0,   12,    0,    0,    0,
        0,    0,   46,    0,    0,    0,    0,    0,    0,    0,
        0,   36,    0,   62,    0,    1,   51,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   21,   47,

        0,   17,    0,    0,   28,    2,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   22,   48,    0,   18,
        7,    0,   43,   73,    0,    0,    0,    0,    0,    0,
        0,   33,    0,    0,    8,    0,   44,   74,    0,    0,
        0,    0,    0,   34,    0,   25,   15,    0,   53,    0,
        0,    0,    0,    0,    0,   26,   16,   54,    0,    0,
        0,    0,    0,    0,    0,    0,   13,   23,    0,    0,
        0,   14,   24,    0,    0,    0,    0,    0,    0,    0,
        0,   59,   41,    0,    0,    0,   42,    0,    0,    0,
       60,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   75,    0,   58,   57,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    1,    5,
        5,    1,    1,    5,    5,    5,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    5,   10,
       11,   12,    5,    1,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       14,   14,   14,   14,   15,   14,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   13,   25,   26,   27,   28,
       29,   30,   13,   31,   32,   33,   34,   35,   36,   37,
       38,   39,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    1,    1,
        5,    1,    1,    1,    5,    1,    5,    1,    1,    1,
        1,    1,    1,    5,    1,    1,    1,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    5,    1,    1,    1,    5,    1,    5,    1,
        1,    1,    1,    1,    1,    5,    1,    1,    1,    1,
        5,    1,    1,    5,    5,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[40] =
    {   0,
        1,    1,    2,    1,    3,    3,    1,    4,    3,    1,
        1,    1,    4,    5,    6,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[624] =
    {   0,
        0,    0,  943,  944,   38,  944,   35,   38,   46,   55,
       93,  909,  908,   61,   58,   61,   62,    0,  104,  109,
      124,  139,  139,  147,   48,  924,   55,  915,  909,   94,
      913,  159,  907,  156,  175,  911,  914,  178,  903,  899,
       83,  199,  209,  210,  214,  215,  208,   82,  915,  140,
      906,  900,  201,  904,  215,  898,  212,  231,  906,  893,
      893,  890,  889,  888,   93,  887,   29,  886,  887,  891,
      126,  895,  895,  886,  882,  881,  882,  878,  873,  890,
      880,  121,  875,  888,  875,  874,  871,  881,  867,  880,
      882,  234,  242,  159,  272,  889,  252,  864,  876,  861,

      860,  859,  203,  858,  196,  857,  858,  862,  857,  865,
      865,  856,  852,  851,  852,  848,  843,  860,  850,  234,
      845,  858,  845,  844,  841,  851,  837,  853,  835,  847,
      842,  842,  826,  836,  824,  841,  836,  836,  827,  825,
      837,  833,  825,  824,  825,  826,  834,  817,  820,  814,
      834,  812,  814,  810,  822,  813,  814,  820,  809,  808,
      820,  809,  814,  802,  283,  255,  261,  298,  313,  824,
      288,  798,  799,  805,  805,  789,  799,  787,  804,  799,
      799,  790,  788,  800,  789,  788,  789,  790,  798,  781,
      784,  778,  798,  776,  778,  774,  786,  777,  778,  784,

      773,  772,  784,  773,  767,  766,  764,  777,  765,  781,
      772,  760,  778,  763,  772,  749,  753,  765,  764,  752,
      225,  758,   80,  769,  751,  759,  760,  944,  753,  169,
      756,  755,  758,  753,  734,  738,  736,  750,  748,  738,
      754,  758,  321,  332,  262,  317,  319,  347,  352,  367,
        0,  382,  756,  336,  732,  742,  743,  731,  747,  738,
      726,  744,  729,  738,  715,  719,  731,  719,  228,  725,
      736,  735,  717,  725,  726,  944,  719,  259,  722,  721,
      724,  719,  700,  704,  702,  716,  714,  721,  716,  699,
      704,  698,  944,  700,  703,  944,  714,  693,  691,  695,

      691,  702,  687,  944,  692,  679,  680,  944,  944,  688,
      703,  685,  684,  681,  691,  698,  676,  681,  695,  694,
      693,  674,  691,  690,  682,  944,    0,  693,  692,  390,
      405,    0,  420,  435,    0,    0,  447,  682,  665,  670,
      664,  944,  666,  669,  944,  680,  659,  657,  661,  657,
      654,  944,  659,  646,  944,  944,  656,  671,  653,  652,
      649,  659,  666,  644,  649,  663,  662,  661,  642,  659,
      658,  944,  651,  656,  647,  654,  632,  642,  944,  639,
      645,  645,  648,  643,  642,  641,  636,  629,  626,  944,
      634,  624,  635,  618,  944,  637,  628,  944,  944,  944,

      635,  944,  944,  630,  462,  638,  636,  349,    0,  625,
      610,  621,  628,  606,  616,  944,  613,  619,  619,  622,
      617,  616,  611,  602,  944,  610,  600,  611,  594,  944,
      613,  604,  944,  944,  944,  611,  944,  944,  589,  944,
      609,  944,  608,  596,  586,  591,  589,  944,  582,  586,
      587,  593,  587,  594,  589,  596,  595,  586,  944,  593,
      944,  571,  393,  570,  590,  589,  944,  588,  576,  566,
      571,  569,  944,  567,  568,  574,  576,  571,  578,  577,
      568,  944,  575,  944,  574,  944,  944,  552,  572,  571,
      562,  565,  547,  546,  552,  549,  549,  563,  944,  944,

      556,  944,  557,  560,  944,  944,  944,  538,  558,  557,
      548,  534,  533,  539,  537,  551,  944,  944,  544,  944,
      944,  549,  944,  944,  548,  555,  546,  541,  532,  530,
      534,  944,  520,  548,  944,  535,  944,  944,  529,  523,
      510,  490,  488,  944,  466,  944,  944,  472,  944,  473,
      451,  471,  463,  458,  444,  944,  944,  944,  443,  418,
      431,  426,  409,  402,  390,  395,  944,  944,  389,  382,
      371,  944,  944,  377,  381,  378,  354,  354,  355,  358,
      345,  944,  944,  335,  330,  334,  944,  304,  300,  285,
      944,  291,  297,  281,  259,  259,  186,  191,  182,  150,

      112,  944,   92,  944,  944,  944,  475,  481,   76,  485,
      491,  497,  500,  506,  512,  515,  518,  524,  527,  533,
       45,  539,  545
    } ;

static const flex_int16_t yy_def[624] =
    {   0,
      606,    1,  606,  606,  606,  606,  607,  607,  608,  606,
      608,   11,   11,  606,  607,  607,  607,  609,  610,  610,
      611,  611,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  610,   22,   22,
      607,  612,   22,   22,   22,   22,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,   22,   22,  613,  612,  609,  610,  606,  606,  606,

      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  610,   22,   22,  614,  615,   95,
       22,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,

      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  610,  610,   22,  616,  617,  618,  616,  617,
      619,  620,   95,   22,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,

      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  621,  606,  606,  610,
      622,  619,  618,  620,  333,  250,  622,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,

      606,  606,  606,  606,  623,  606,  337,  616,  337,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,   95,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,

      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,

      606,  606,  606,  606,  606,    0,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606
    } ;

static const flex_int16_t yy_nxt[984] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,    7,   10,
        4,    4,   11,    4,    7,   11,   11,   11,   11,   11,
       12,   11,   13,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   14,
       16,   14,   17,  606,  137,  606,   18,   18,  405,   18,
       19,   20,   18,   21,   19,   18,   18,   18,  138,   18,
       19,   23,   14,   16,   14,   17,   41,   41,   17,   17,
       24,   64,   25,   26,   27,   28,   65,   29,   30,   42,
       31,   67,   68,  307,   32,   33,   34,   35,  606,   36,
      606,  308,   37,   18,   18,  605,   18,   19,   38,   18,

       21,   19,   18,   18,   18,  102,   18,   19,   15,   16,
      103,   43,   15,   15,  606,  604,   42,   15,   15,  134,
       71,   72,  135,   15,   18,   18,   73,   18,   19,   20,
       18,   45,   19,   18,   18,   18,  154,   18,   19,   18,
       18,  142,   18,   19,   38,   18,   45,   19,   18,   18,
       18,  155,   18,   19,   47,  143,   48,   49,   50,   51,
      603,   52,   53,   60,   54,   61,  105,  106,   55,   56,
       57,   58,  169,  169,   75,   80,   59,   62,   76,   81,
       63,   77,   15,   41,  314,   43,   15,   78,   82,   83,
       84,   85,   15,  602,  315,   86,   87,   88,   89,   18,

       18,  601,   18,   18,   18,   94,  600,   96,   18,   18,
       18,  180,   18,   18,   20,   94,   94,   97,   97,   20,
       94,   94,   97,   97,   98,  181,   99,  109,  110,  177,
      113,  118,  178,  111,  114,  119,  304,  115,  100,  352,
       94,  101,  165,  116,  120,  121,  122,  123,   94,  196,
       97,  124,  125,  126,  127,  305,   15,   16,  353,  171,
       15,   94,  599,  243,  197,  166,   15,   94,   94,  244,
      330,  167,   18,   18,  361,   18,   18,   18,   94,  598,
       96,   18,   18,   18,  362,   18,   18,   15,   16,  242,
      171,   15,  245,   20,   94,  254,   97,   15,  246,  246,

      597,  246,  246,  246,  247,  596,  249,  246,  246,  246,
      595,  250,  250,  251,  251,  594,  251,  251,  251,  251,
      593,  251,  251,  251,  251,   15,   16,  328,  171,   15,
      332,  332,  334,  334,  592,   15,   15,   16,  329,  171,
       15,   20,   94,  254,   97,  591,   15,  246,  246,  590,
      246,  246,  246,  247,  589,  249,  246,  246,  246,  337,
      336,  336,  332,  332,  588,  332,  332,  251,  251,  587,
      251,  251,  251,  251,  586,  251,  251,  251,  251,  585,
      334,  334,  251,  251,  584,  251,  251,  251,  251,  583,
      251,  251,  251,  251,   15,   16,  406,  171,   15,   18,

      582,   18,  581,  580,   15,   18,   18,  579,   18,   18,
       18,   94,  578,   96,   18,   18,   18,  577,  408,  408,
      246,  246,  576,  246,  246,  246,  247,  575,  249,  246,
      246,  246,  574,  336,  336,  251,  251,  573,  251,  251,
      251,  251,  572,  251,  251,  251,  251,   18,   18,  571,
       18,   18,   18,   94,  409,   96,   18,   18,   18,  570,
      408,  408,   18,   18,  569,   18,   18,   18,   18,  568,
       18,   18,   18,   18,  567,   18,   18,   15,   15,  566,
       15,   22,  565,   22,   22,   22,   22,   44,   44,  564,
       44,   46,  563,   46,   46,   46,   46,   95,  562,   95,

       95,   95,   95,  168,  168,  168,  248,  561,  248,  248,
      248,  248,  252,  560,  252,  252,  252,  252,  331,  331,
      331,  333,  333,  333,  335,  559,  335,  335,  335,  335,
      332,  332,  332,  334,  558,  334,  334,  334,  334,  407,
      557,  407,  407,  407,  407,  463,  556,  463,  463,  463,
      463,  555,  554,  553,  552,  551,  550,  549,  548,  547,
      546,  545,  544,  543,  542,  541,  540,  539,  538,  537,
      536,  535,  534,  533,  532,  531,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  511,  510,  509,  508,  507,

      506,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  473,  472,  471,  470,  469,  468,  467,
      466,  465,  464,  407,  327,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  327,  327,

      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  360,  359,  358,  357,  356,  355,  354,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  253,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  313,  312,  311,  310,
      309,  306,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,

      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  253,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      179,  176,  175,  174,  173,  172,  170,  164,  163,  162,

      161,  160,  159,  158,  157,  156,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  141,  140,  139,  136,
      133,  132,  131,  130,  129,  128,  117,  112,  108,  107,
      104,   93,   92,   91,   90,   79,   74,   70,   69,   66,
       40,   39,  606,    3,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606
    } ;

static const flex_int16_t yy_chk[984] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        7,    5,    7,    8,   67,    8,    9,    9,  621,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   67,    9,
        9,   10,   14,   15,   14,   15,   16,   17,   16,   17,
       10,   25,   10,   10,   10,   10,   25,   10,   10,  609,
       10,   27,   27,  223,   10,   10,   10,   10,   41,   10,
       41,  223,   10,   11,   11,  603,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   48,   11,   11,   19,   19,
       48,   19,   19,   20,   20,  601,   20,   20,   19,   65,
       30,   30,   65,   20,   21,   21,   30,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   82,   21,   21,   22,
       22,   71,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   82,   22,   22,   23,   71,   23,   23,   23,   23,
      600,   23,   23,   24,   23,   24,   50,   50,   23,   23,
       23,   23,   94,   94,   32,   34,   23,   24,   32,   34,
       24,   32,   38,   38,  230,   38,   38,   32,   34,   34,
       35,   35,   38,  599,  230,   35,   35,   35,   35,   42,

       42,  598,   42,   42,   42,   42,  597,   42,   42,   42,
       42,  105,   42,   42,   43,   43,   44,   43,   44,   45,
       45,   46,   45,   46,   47,  105,   47,   53,   53,  103,
       55,   57,  103,   53,   55,   57,  221,   55,   47,  269,
       92,   47,   92,   55,   57,   57,   58,   58,   93,  120,
       93,   58,   58,   58,   58,  221,   97,   97,  269,   97,
       97,  166,  596,  166,  120,   92,   97,  167,  245,  167,
      245,   93,   95,   95,  278,   95,   95,   95,   95,  595,
       95,   95,   95,   95,  278,   95,   95,  165,  165,  165,
      165,  165,  167,  171,  171,  171,  171,  165,  168,  168,

      594,  168,  168,  168,  168,  593,  168,  168,  168,  168,
      592,  168,  168,  169,  169,  590,  169,  169,  169,  169,
      589,  169,  169,  169,  169,  243,  243,  243,  243,  243,
      246,  246,  247,  247,  588,  243,  244,  244,  244,  244,
      244,  254,  254,  254,  254,  586,  244,  248,  248,  585,
      248,  248,  248,  248,  584,  248,  248,  248,  248,  249,
      248,  248,  408,  408,  581,  249,  249,  250,  250,  580,
      250,  250,  250,  250,  579,  250,  250,  250,  250,  578,
      250,  250,  252,  252,  577,  252,  252,  252,  252,  576,
      252,  252,  252,  252,  330,  330,  330,  330,  330,  463,

      575,  463,  574,  571,  330,  331,  331,  570,  331,  331,
      331,  331,  569,  331,  331,  331,  331,  566,  331,  331,
      333,  333,  565,  333,  333,  333,  333,  564,  333,  333,
      333,  333,  563,  333,  333,  334,  334,  562,  334,  334,
      334,  334,  561,  334,  334,  334,  334,  337,  337,  560,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  559,
      337,  337,  405,  405,  555,  405,  405,  405,  405,  554,
      405,  405,  405,  405,  553,  405,  405,  607,  607,  552,
      607,  608,  551,  608,  608,  608,  608,  610,  610,  550,
      610,  611,  548,  611,  611,  611,  611,  612,  545,  612,

      612,  612,  612,  613,  613,  613,  614,  543,  614,  614,
      614,  614,  615,  542,  615,  615,  615,  615,  616,  616,
      616,  617,  617,  617,  618,  541,  618,  618,  618,  618,
      619,  619,  619,  620,  540,  620,  620,  620,  620,  622,
      539,  622,  622,  622,  622,  623,  536,  623,  623,  623,
      623,  534,  533,  531,  530,  529,  528,  527,  526,  525,
      522,  519,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  504,  503,  501,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  485,  483,  481,  480,  479,
      478,  477,  476,  475,  474,  472,  471,  470,  469,  468,

      466,  465,  464,  462,  460,  458,  457,  456,  455,  454,
      453,  452,  451,  450,  449,  447,  446,  445,  444,  443,
      441,  439,  436,  432,  431,  429,  428,  427,  426,  424,
      423,  422,  421,  420,  419,  418,  417,  415,  414,  413,
      412,  411,  410,  407,  406,  404,  401,  397,  396,  394,
      393,  392,  391,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  378,  377,  376,  375,  374,  373,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  354,  353,  351,  350,  349,  348,
      347,  346,  344,  343,  341,  340,  339,  338,  329,  328,

      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  307,  306,  305,  303,
      302,  301,  300,  299,  298,  297,  295,  294,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  277,  275,  274,  273,  272,  271,  270,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  253,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  229,  227,  226,  225,
      224,  222,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,

      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  170,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  119,  118,  117,  116,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      104,  102,  101,  100,   99,   98,   96,   91,   90,   89,

       88,   87,   86,   85,   84,   83,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   72,   70,   69,   68,   66,
       64,   63,   62,   61,   60,   59,   56,   54,   52,   51,
       49,   40,   39,   37,   36,   33,   31,   29,   28,   26,
       13,   12,    3,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606,  606,  606,  606,  606,  606,  606,  606,
      606,  606,  606
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
    #include "grammar.tab.h"
#line 865 "lex.yy.c"
/*
protocolo (http:\/\/|https:\/\/|ftp:\/\/|ftps:\/\/)?
dominio ([a-zA-Z0-9]+.)+[a-zA-Z0-9]+
puerto (:[0-9]+)?
ruta ((\/)|((\/)([a-zA-z0-9])+).([a-zA-z0-9])+)?
*/
#line 872 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 17 "scanner.l"

#line 1091 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 607 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 944 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 18 "scanner.l"
{ printf("Article Apertura: %s\n", yytext);         }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 19 "scanner.l"
{ printf("Article Cierre: %s\n", yytext);           }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 20 "scanner.l"
{ printf("Info Apertura: %s\n", yytext);            }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 21 "scanner.l"
{ printf("Info Cierre: %s\n", yytext);              }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "scanner.l"
{ printf("Title Apertura: %s\n", yytext);           }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "scanner.l"
{ printf("Title Cierre: %s\n", yytext);             }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 24 "scanner.l"
{ printf("Abstract Apertura: %s\n", yytext);        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 25 "scanner.l"
{ printf("Abstract Cierre: %s\n", yytext);          }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "scanner.l"
{ printf("Para Apertura: %s\n", yytext);            }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "scanner.l"
{ printf("Para Cierre: %s\n", yytext);              }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "scanner.l"
{ printf("Author Apertura: %s\n", yytext);          }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "scanner.l"
{ printf("Author Cierre: %s\n", yytext);            }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "scanner.l"
{ printf("PersonName Apertura: %s\n", yytext);      }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "scanner.l"
{ printf("PersonName Cierre: %s\n", yytext);        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "scanner.l"
{ printf("Firstname Apertura: %s\n", yytext);       }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "scanner.l"
{ printf("Firstname Cierre: %s\n", yytext);         }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "scanner.l"
{ printf("Surname Apertura: %s\n", yytext);         }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "scanner.l"
{ printf("Surname Cierre: %s\n", yytext);           }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "scanner.l"
{ printf("Date Apertura: %s\n", yytext);            }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "scanner.l"
{ printf("Date Cierre: %s\n", yytext);              }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "scanner.l"
{ printf("Section Apertura: %s\n", yytext);         }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 39 "scanner.l"
{ printf("Section Cierre: %s\n", yytext);           }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 40 "scanner.l"
{ printf("SimpleSect Apertura: %s\n", yytext);      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 41 "scanner.l"
{ printf("SimpleSect Cierre: %s\n", yytext);        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 42 "scanner.l"
{ printf("Copyright Apertura: %s\n", yytext);       }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 43 "scanner.l"
{ printf("Copyright Cierre: %s\n", yytext);         }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "scanner.l"
{ printf("Address Apertura: %s\n", yytext);         }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "scanner.l"
{ printf("Address Cierre: %s\n", yytext);           }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "scanner.l"
{ printf("City Apertura: %s\n", yytext);            }   
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "scanner.l"
{ printf("City Cierre: %s\n", yytext);              }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "scanner.l"
{ printf("State Apertura: %s\n", yytext);           }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "scanner.l"
{ printf("State Cierre: %s\n", yytext);             }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "scanner.l"
{ printf("Postcode Apertura: %s\n", yytext);        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "scanner.l"
{ printf("Postcode Cierre: %s\n", yytext);          } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "scanner.l"
{ printf("Street Apertura: %s\n", yytext);          }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "scanner.l"
{ printf("Street Cierre: %s\n", yytext);            }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "scanner.l"
{ printf("Email Apertura: %s\n", yytext);           }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "scanner.l"
{ printf("Email Cierre: %s\n", yytext);             }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 56 "scanner.l"
{ printf("Phone Apertura: %s\n", yytext);           }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "scanner.l"
{ printf("PhoneCierre: %s\n", yytext);              }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "scanner.l"
{ printf("ItemizedList Apertura: %s\n", yytext);    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "scanner.l"
{ printf("ItemizedList Cierre: %s\n", yytext);      }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "scanner.l"
{ printf("Emphasis Apertura: %s\n", yytext);        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 61 "scanner.l"
{ printf("Emphasis Cierre: %s\n", yytext);          }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 62 "scanner.l"
{ printf("Holder Apertura: %s\n", yytext);          }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "scanner.l"
{ printf("Holder Cierre: %s\n", yytext);            }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "scanner.l"
{ printf("SimPara Apertura: %s\n", yytext);         }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "scanner.l"
{ printf("Simpara Cierre: %s\n", yytext);           }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "scanner.l"
{ printf("Year Apertura: %s\n", yytext);            }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "scanner.l"
{ printf("Year Cierre: %s\n", yytext);              } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 68 "scanner.l"
{ printf("Comment Apertura: %s\n", yytext);         }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 69 "scanner.l"
{ printf("Comment Cierre: %s\n", yytext);           }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 70 "scanner.l"
{ printf("Important Apertura: %s\n", yytext);       }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "scanner.l"
{ printf("Important Cierre: %s\n", yytext);         }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "scanner.l"
{ printf("Link Apertura: %s\n", yytext);            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "scanner.l"
{ printf("Link Cierre: %s\n", yytext);              }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "scanner.l"
{ printf("Videodata : %s\n", yytext);               }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "scanner.l"
{ printf("Imagedata: %s\n", yytext);                }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "scanner.l"
{ printf("InformalTable Apertura: %s\n", yytext);   }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "scanner.l"
{ printf("InformalTable Cierre: %s\n", yytext);     }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "scanner.l"
{ printf("Tgroup Apertura: %s\n", yytext);          }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "scanner.l"
{ printf("Tgroup Cierre: %s\n", yytext);            }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "scanner.l"
{ printf("Row Apertura: %s\n", yytext);             }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "scanner.l"
{ printf("Row Cierre: %s\n", yytext);               }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "scanner.l"
{ printf("Table Apertura: %s\n", yytext);           }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "scanner.l"
{ printf("Table Cierre: %s\n", yytext);             }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "scanner.l"
{ printf("Thead Apertura: %s\n", yytext);           }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "scanner.l"
{ printf("Thead Cierre: %s\n", yytext);             }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 86 "scanner.l"
{ printf("Tfoot Apertura: %s\n", yytext);           }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 87 "scanner.l"
{ printf("Tfoot Cierre: %s\n", yytext);             }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 88 "scanner.l"
{ printf("Tbody Apertura: %s\n", yytext);           }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 89 "scanner.l"
{ printf("Tbody Cierre: %s\n", yytext);             }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 90 "scanner.l"
{ printf("EntryTBL Apertura: %s\n", yytext);        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 91 "scanner.l"
{ printf("EntryTBL Cierre: %s\n", yytext);          }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 92 "scanner.l"
{ printf("Link: %s\n", yytext);                     }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 93 "scanner.l"
{ printf("Es una URL: %s\n", yytext);                }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 94 "scanner.l"
{ printf("Texto: %s\n", yytext);                  }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 95 "scanner.l"
{ /* Ignorar saltos de línea */ }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 96 "scanner.l"
{ /* Ignorar espacios y tabuladores */ }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 97 "scanner.l"
ECHO;
	YY_BREAK
#line 1549 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 607 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 607 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 606);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 97 "scanner.l"

/* \n                      {                                                   } */
int main(){
    yylex();
}

